# Generated by Django 5.0.6 on 2024-06-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrande',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
